export const INVENTORIES_LOADING = 'INVENTORIES_LOADING';
export const ADD_INVENTORIES = 'ADD_INVENTORIES';
export const INVENTORIES_FAILED ="INVENTORIES_FAILED";

export const ADD_REVIEWS = 'ADD_REVIEWS';
export const REVIEWS_FAILED = 'REVIEWS_FAILED';

export const BRANDS_LOADING ='BRANDS_LOADING';
export const ADD_BRANDS = 'ADD_BRANDS';
export const BRANDS_FAILED = "BRANDS_FAILED";



